name: Generate PDF from Markdown and Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Pandoc
      - name: Set up Pandoc
        run: sudo apt-get install -y pandoc

      # Step 3: Install LaTeX
      - name: Install LaTeX
        run: sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-extra

      # Step 4: Generate PDFs
      - name: Generate PDFs
        run: |
          mkdir -p build
          pandoc statutes.md -o build/statutes.pdf --pdf-engine=xelatex --number-sections -V fontsize=11pt -H config/header.tex --lua-filter=config/custom-links.lua
          pandoc rules-of-procedure.md -o build/rules-of-procedure.pdf --pdf-engine=xelatex --number-sections -V fontsize=11pt -H config/header.tex --lua-filter=config/custom-links.lua

      # Step 5: Commit the build folder to the 'deploy' branch
      - name: Deploy to Deployment Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -B deploy
          git add build/
          git commit -m "Deploy PDFs [skip ci]" || echo "No changes to commit"
          git push origin deploy --force