name: Generate PDF from Markdown

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Pandoc
        run: sudo apt-get install -y pandoc
        
      - name: Install LaTeX
        run: sudo apt-get install -y texlive texlive-latex-extra
        
      - name: Generate PDF
        run: pandoc statutes.md -o statutes.pdf --pdf-engine=xelatex --toc --toc-depth=2 --number-sections -V geometry:margin=1in -V fontsize=11pt -V documentclass=article -V linkcolor=blue -V urlcolor=blue

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: statutes.pdf
